#!/usr/bin/zsh
if [ -d ~/.zsh ]
then
  echo "\033[0;33mКонфиг zsh уже установлен.\033[0m Удалите ~/.zsh для продолжения установки."
  exit
fi

if [ -d ~/.vim ]
then
  echo "\033[0;33mКонфиг vim уже установлен.\033[0m Удалите ~/.vim для продолжения установки."
  exit
fi

echo "\033[0;34mКлонирование конфигов Zsh и Vim...\033[0m"
/usr/bin/env git clone https://github.com/ademaro/dotfiles.git /tmp/dotfiles
mv /tmp/dotfiles/.zsh* ~/
mv /tmp/dotfiles/.vim* ~/

rm -rf /tmp/dotfiles
