#!/bin/sh
if [ -d ~/.zsh ]
then
  echo "$(tput setaf 1)Конфиг zsh уже установлен.$(tput sgr0) Удалите ~/.zsh для продолжения установки."
  exit
fi

if [ -d ~/.vim ]
then
  echo "$(tput setaf 1)Конфиг vim уже установлен.$(tput sgr0) Удалите ~/.vim для продолжения установки."
  exit
fi

if command -v git
then
  echo "$(tput setaf 2)Клонирование конфигов Zsh и Vim...$(tput sgr0)"

  /usr/bin/env git clone https://github.com/ademaro/dotfiles.git /tmp/dotfiles
  mv /tmp/dotfiles/.zsh* ~/
  mv /tmp/dotfiles/.vim* ~/

  rm -rf /tmp/dotfiles
  echo "$(tput setaf 2)Установка прошла успешно$(tput sgr0)"
else
  echo "$(tput setaf 1)git не установлен.$(tput sgr0) Установите, например: apt-get install git для продолжения установки."
fi
